# Generated by Django 5.0.7 on 2024-08-27 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='inventroy',
            new_name='inventory',
        ),
    ]
