# Generated by Django 5.0.7 on 2024-09-13 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='counted_view',
        ),
    ]
