# Generated by Django 5.0.7 on 2024-09-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_truncated_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='admin_selected',
            field=models.BooleanField(default=False),
        ),
    ]
